version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
        - checkout
        - run : python main.py
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run : echo "deploying to production server"

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
